```js
Algoritmo " cadastro de cliente"

Var
nomeCompleto, email, senha: caracter
Inicio
	escreva("Digite o seu nome completo: ")
		leia(nomeCompleto)

		escreva("Digite seu e-mail: ")
		leia(email)

		escreva("Digite uma senha: ")
		leia(senha)

		escreva("Parabéns ", nomeCompleto , "Sua conta foi criada e um E-mail foi enviado para ", email , "Muito obrigado por se cadastrar no nosso site!")
	}
Fimalgoritmo

```
